#include "mainwindow.h"
#include "ui_mainwindow.h"
#include "block.h"

#include <Components/motor.h>
#include <Components/battery.h>
#include <Components/lightbulb.h>
#include <Components/resistor.h>

#include <QInputDialog>

/*--------------Default Functions-----------------*/

MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);
    impl = new Impl(ui->backgroundLabel, ui->wireButton, ui->statusBar);
}

MainWindow::~MainWindow()
{
    delete ui;
}

/*---------Button Functions Connection------------*/
/*--------------Generated by Qt---------------*/

void MainWindow::on_batteryButton_clicked()
{
    bool ok = false;
    double value = QInputDialog::getDouble(this, "", "Please enter the battery voltage (volt)", 1.5,
                                           0, 2147483647, 1, &ok);

    if (ok) {
        impl->addComponent("Battery", value);
    }
}

void MainWindow::on_resistanceButton_clicked()
{
    bool ok = false;
    double value = QInputDialog::getDouble(this, "", "Please enter the resistance value (ohm)", 1000,
                                           0, 2147483647, 1, &ok);

    if (ok) {
        impl->addComponent("Resistance", value);
    }
}

void MainWindow::on_motorButton_clicked()
{
    impl->addComponent("Motor");
}

void MainWindow::on_bulbButton_clicked()
{
    impl->addComponent("LightBulb");
}

void MainWindow::on_wireButton_toggled(bool checked)
{
    impl->showWirePalette(checked);
}

/*--------End of Button Functions Connection-------*/

void MainWindow::on_checkBox_stateChanged(int arg1)
{
    impl->setDisplay(arg1 > 0);
}
